plugins {
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    // Only JUnit for now; other deps will be added later
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
}

application {
    mainClass = 'com.recomind.App'
}

tasks.named('test') {
    useJUnitPlatform()
}

shadowJar {
    archiveBaseName.set('recomind-all')
    archiveClassifier.set('')
    archiveVersion.set('')
    mergeServiceFiles()
}
