-- Full schema for RecoMind application
CREATE TABLE IF NOT EXISTS ROLES (
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS USERS (
    ID IDENTITY PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ACTIVE BOOLEAN DEFAULT TRUE,
    ROLE_ID BIGINT,
    CONSTRAINT FK_USERS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);

CREATE TABLE IF NOT EXISTS USER_PREFERENCES (
    USER_ID BIGINT PRIMARY KEY,
    PREFERENCE_JSON CLOB,
    CONSTRAINT FK_PREF_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CATEGORIES (
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ITEMS (
    ID IDENTITY PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    TAGS VARCHAR(255),
    DESCRIPTION CLOB,
    IMAGE_URL VARCHAR(512),
    PRICE DECIMAL(10,2),
    CONSTRAINT FK_ITEMS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);

CREATE TABLE IF NOT EXISTS INTERACTIONS (
    ID IDENTITY PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    RATING INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_INTERACTION_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_INTERACTION_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID)
);

CREATE TABLE IF NOT EXISTS RECOMMENDATIONS (
    USER_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    SCORE DOUBLE,
    PRIMARY KEY (USER_ID, ITEM_ID),
    CONSTRAINT FK_RECOMMEND_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_RECOMMEND_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID)
);

CREATE TABLE IF NOT EXISTS SYSTEM_SETTINGS (
    SETTING_KEY VARCHAR(100) PRIMARY KEY,
    SETTING_VALUE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS AUDIT_LOG (
    ID IDENTITY PRIMARY KEY,
    USER_ID BIGINT,
    ACTION VARCHAR(255) NOT NULL,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DETAILS CLOB,
    CONSTRAINT FK_AUDIT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE SET NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IF NOT EXISTS IDX_ITEMS_TITLE ON ITEMS(TITLE);
CREATE INDEX IF NOT EXISTS IDX_INTERACTIONS_USER ON INTERACTIONS(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_INTERACTIONS_ITEM ON INTERACTIONS(ITEM_ID);
