-- src/main/resources/schema.sql
CREATE TABLE IF NOT EXISTS USERS (
    ID IDENTITY PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ITEMS (
    ID IDENTITY PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(100),
    TAGS VARCHAR(255),
    DESCRIPTION CLOB,
    IMAGE_URL VARCHAR(512),
    PRICE DECIMAL(10,2)
);
