-- src/main/resources/seed.sql
-- Roles
INSERT INTO ROLES (NAME) VALUES ('ADMIN');
INSERT INTO ROLES (NAME) VALUES ('USER');

-- Users (12 users, with BCrypt real hashes)
INSERT INTO USERS (EMAIL, PASSWORD_HASH, ACTIVE, ROLE_ID) VALUES ('admin@recomind.com', '$2a$10$gl/GcezDoKytzePEm2TDX.hCEGcOX7Ui5uD07jcqzi9ZW99iETOFa', TRUE, (SELECT ID FROM ROLES WHERE NAME='ADMIN'));
INSERT INTO USERS (EMAIL, PASSWORD_HASH, ACTIVE, ROLE_ID) VALUES ('user@recomind.com', '$2a$10$1rZ1Pjlubp2IeU5gnmkniOU6BkfBDoAtNhx8MLWdESf1y8QbVy8Lq', TRUE, (SELECT ID FROM ROLES WHERE NAME='USER'));
INSERT INTO USERS (EMAIL, PASSWORD_HASH, ACTIVE, ROLE_ID) VALUES ('demo1@recomind.com', '$2a$10$Gs/CJVaXjco0kF8M63OycONmmkeMdkOVqzHgMeF/q3.y0Wp8iqEn2', TRUE, (SELECT ID FROM ROLES WHERE NAME='USER'));
INSERT INTO USERS (EMAIL, PASSWORD_HASH, ACTIVE, ROLE_ID) VALUES ('demo2@recomind.com', '$2a$10$Gs/CJVaXjco0kF8M63OycONmmkeMdkOVqzHgMeF/q3.y0Wp8iqEn2', TRUE, (SELECT ID FROM ROLES WHERE NAME='USER'));
INSERT INTO USERS (EMAIL, PASSWORD_HASH, ACTIVE, ROLE_ID) VALUES ('demo3@recomind.com', '$2a$10$Gs/CJVaXjco0kF8M63OycONmmkeMdkOVqzHgMeF/q3.y0Wp8iqEn2', TRUE, (SELECT ID FROM ROLES WHERE NAME='USER'));
INSERT INTO USERS (EMAIL, PASSWORD_HASH, ACTIVE, ROLE_ID) VALUES ('demo4@recomind.com', '$2a$10$Gs/CJVaXjco0kF8M63OycONmmkeMdkOVqzHgMeF/q3.y0Wp8iqEn2', TRUE, (SELECT ID FROM ROLES WHERE NAME='USER'));
INSERT INTO USERS (EMAIL, PASSWORD_HASH, ACTIVE, ROLE_ID) VALUES ('demo5@recomind.com', '$2a$10$Gs/CJVaXjco0kF8M63OycONmmkeMdkOVqzHgMeF/q3.y0Wp8iqEn2', TRUE, (SELECT ID FROM ROLES WHERE NAME='USER'));
INSERT INTO USERS (EMAIL, PASSWORD_HASH, ACTIVE, ROLE_ID) VALUES ('demo6@recomind.com', '$2a$10$Gs/CJVaXjco0kF8M63OycONmmkeMdkOVqzHgMeF/q3.y0Wp8iqEn2', TRUE, (SELECT ID FROM ROLES WHERE NAME='USER'));
INSERT INTO USERS (EMAIL, PASSWORD_HASH, ACTIVE, ROLE_ID) VALUES ('demo7@recomind.com', '$2a$10$Gs/CJVaXjco0kF8M63OycONmmkeMdkOVqzHgMeF/q3.y0Wp8iqEn2', TRUE, (SELECT ID FROM ROLES WHERE NAME='USER'));
INSERT INTO USERS (EMAIL, PASSWORD_HASH, ACTIVE, ROLE_ID) VALUES ('demo8@recomind.com', '$2a$10$Gs/CJVaXjco0kF8M63OycONmmkeMdkOVqzHgMeF/q3.y0Wp8iqEn2', TRUE, (SELECT ID FROM ROLES WHERE NAME='USER'));
INSERT INTO USERS (EMAIL, PASSWORD_HASH, ACTIVE, ROLE_ID) VALUES ('demo9@recomind.com', '$2a$10$Gs/CJVaXjco0kF8M63OycONmmkeMdkOVqzHgMeF/q3.y0Wp8iqEn2', TRUE, (SELECT ID FROM ROLES WHERE NAME='USER'));
INSERT INTO USERS (EMAIL, PASSWORD_HASH, ACTIVE, ROLE_ID) VALUES ('demo10@recomind.com', '$2a$10$Gs/CJVaXjco0kF8M63OycONmmkeMdkOVqzHgMeF/q3.y0Wp8iqEn2', TRUE, (SELECT ID FROM ROLES WHERE NAME='USER'));

-- Categories (6 categories)
INSERT INTO CATEGORIES (NAME) VALUES ('Electronics');
INSERT INTO CATEGORIES (NAME) VALUES ('Books');
INSERT INTO CATEGORIES (NAME) VALUES ('Clothing');
INSERT INTO CATEGORIES (NAME) VALUES ('Home');
INSERT INTO CATEGORIES (NAME) VALUES ('Sports');
INSERT INTO CATEGORIES (NAME) VALUES ('Toys');

-- Items (60 items, 10 per category) with titles, tags, descriptions, price
INSERT INTO ITEMS (TITLE, CATEGORY_ID, TAGS, DESCRIPTION, PRICE) SELECT
  'Electro Gadget '||X,
  (SELECT ID FROM CATEGORIES WHERE NAME='Electronics'),
  'gadget,tech',
  'Highâ€‘quality electronic gadget number '||X,
  19.99+MOD(X,5)
FROM SYSTEM_RANGE(1,10);
INSERT INTO ITEMS (TITLE, CATEGORY_ID, TAGS, DESCRIPTION, PRICE) SELECT
  'Book Title '||X,
  (SELECT ID FROM CATEGORIES WHERE NAME='Books'),
  'book,reading',
  'Engaging book number '||X,
  9.99+MOD(X,3)
FROM SYSTEM_RANGE(1,10);
INSERT INTO ITEMS (TITLE, CATEGORY_ID, TAGS, DESCRIPTION, PRICE) SELECT
  'Clothing Item '||X,
  (SELECT ID FROM CATEGORIES WHERE NAME='Clothing'),
  'fashion,clothing',
  'Stylish clothing item number '||X,
  29.99+MOD(X,4)
FROM SYSTEM_RANGE(1,10);
INSERT INTO ITEMS (TITLE, CATEGORY_ID, TAGS, DESCRIPTION, PRICE) SELECT
  'Home Good '||X,
  (SELECT ID FROM CATEGORIES WHERE NAME='Home'),
  'home,decor',
  'Useful home product number '||X,
  49.99+MOD(X,6)
FROM SYSTEM_RANGE(1,10);
INSERT INTO ITEMS (TITLE, CATEGORY_ID, TAGS, DESCRIPTION, PRICE) SELECT
  'Sport Gear '||X,
  (SELECT ID FROM CATEGORIES WHERE NAME='Sports'),
  'sport,gear',
  'Performance sport gear number '||X,
  39.99+MOD(X,5)
FROM SYSTEM_RANGE(1,10);
INSERT INTO ITEMS (TITLE, CATEGORY_ID, TAGS, DESCRIPTION, PRICE) SELECT
  'Toy Toy '||X,
  (SELECT ID FROM CATEGORIES WHERE NAME='Toys'),
  'toy,fun',
  'Fun toy number '||X,
  14.99+MOD(X,2)
FROM SYSTEM_RANGE(1,10);

-- Interactions (600 rows) with varied types and ratings, timestamps spread over last 60 days
INSERT INTO INTERACTIONS (USER_ID, ITEM_ID, TYPE, RATING, CREATED_AT)
SELECT
  MOD(X, 12) + 1,
  CASE WHEN MOD(X, 5) = 0
       THEN CAST(FLOOR(RAND() * 60) AS INT) + 1
       ELSE (MOD(MOD(X, 12) + 1, 3) * 2 + MOD(CAST(FLOOR(X / 12) AS INT), 2)) * 10
            + CAST(FLOOR(RAND() * 10) AS INT) + 1
  END,
  CASE WHEN MOD(X, 10) IN (0, 1, 2) THEN 'VIEW'
       WHEN MOD(X, 10) IN (3, 4) THEN 'CLICK'
       WHEN MOD(X, 10) IN (5, 6) THEN 'LIKE'
       WHEN MOD(X, 10) = 7 THEN 'DISLIKE'
       WHEN MOD(X, 10) = 8 THEN 'RATING'
       ELSE 'PURCHASE' END,
  CASE WHEN MOD(X, 10) = 8 THEN MOD(CAST(FLOOR(X / 10) AS INT), 5) + 1 END,
  DATEADD('DAY', -MOD(X * 7, 60), CURRENT_TIMESTAMP)
FROM SYSTEM_RANGE(1, 600);

-- System settings defaults
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE) VALUES ('weight.content', '0.4');
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE) VALUES ('weight.collaborative', '0.4');
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE) VALUES ('weight.popularity', '0.2');
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE) VALUES ('recommendation.count', '10');
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE) VALUES ('similarity.threshold', '0.1');
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE) VALUES ('min.interactions', '3');
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE) VALUES ('recompute.interval.minutes', '30');
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE) VALUES ('algorithm.active', 'HYBRID');
